### ISSUE TITLE
pom.xml cleanup and update

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio-thirdparty#7]
The pom.xml for all the main cs-studio repositories should be reasonably similar

1. released/ master branches should use the same version of eclipse and other osgi resources

2. reduce the number of profiles and remove unnecessary ones
2.a. csstudio.local.repo and csstudio.composite.repo seem similar enough that they should be merged. The third party repo only support local while the rest of the repositories support both.
2.b. Keper and luna can be no longer used and the profiles for supporting kepler builds should be clean out

@berryma4

**Comment by kasemir** [comment]
As far as I understand, both csstudio.local.repo and csstudio.composite.repo are ways so say "look here". They would typically point to a local repository, which in turn may be a single big one or a composite of several smaller repos.

But while csstudio.composite.repo is "read-only" (it's content is simply included in the list of repositories used to build CSS), defining csstudio.local.repo also results in writing to that location.

As for simplification, I think we can remove the csstudio.local.repo support. I've transitioned to the csstudio.composite.repo a while ago, and I think I was the last one.
Building once and then setting csstudio.composite.repo to a, well, composite repo that lists all the generated diirt, maven, 3rd party, core, apps repos offers the same functionality while avoiding one more duplication of the artefacts into a separate 'local' repo.

The csstudio.composite.repo doesn't have to be composite nor local. We probably use it that way, but in principle it could point to a single big http://.. repo.
Renaming it to "my.additional.csstudio.repo.to.search.first" would be closer to its actual functionality, but changing its name would mean we need to update our build setups, so I'd rather keep it as csstudio.composite.repo because that's how we tend to use it.

**Comment by berryma4** [comment]
1. yes
2.a. if you look in the repository directory of each module, you will see the main difference in these; local repo mirrors.appends a local directory p2, and it includes all dependencies.
2.b. yes

**Comment by berryma4** [comment]
This ticket should have been in the main repo ....
